version: 2



build:
  os: ubuntu-22.04
  tools:
    nodejs: "20"
    python: "3.12"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs